#:kivy 2.0.0

<ColorBrowser>:
    BoxLayout:
        pos: root.pos
        orientation: "vertical"
        
        ColorPicker:
            id: colorchooser
            
        BoxLayout:
            size_hint_y: 0.2

            Button:
                text: "Apply"
                on_release: root.apply(colorchooser.color)

            Button:
                text: "Cancel"
                on_release: root.cancel()